In [2]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/bike_data.csv')

print(df)

                datetime  season  holiday  workingday  weather   temp   atemp  \
0    2011-09-05 17:00:00       3        1           0        2  27.06  29.545
1    2011-05-17 11:00:00       2        0           1        2  22.96  26.515
2    2011-11-10 09:00:00       4        0           1        2  17.22  21.210
3    2011-10-13 07:00:00       4        0           1        3  22.14  25.760
4    2011-10-15 14:00:00       4        0           0        1  24.60  31.060
..                   ...     ...      ...         ...      ...    ...     ...
430  2011-04-07 16:00:00       2        0           1        1  24.60  31.060
431  2011-09-03 22:00:00       3        0           0        1  27.88  31.820
432  2011-11-12 22:00:00       4        0           0        1  17.22  21.210
433  2012-04-11 23:00:00       2        0           1        1  13.94  15.150
434  2012-01-06 09:00:00       1        0           1        1   9.84  12.120

     humidity  windspeed  casual  registered  count
0          89     7.0015      37          77    114
1          83    27.9993      26         104    130
2          94     7.0015      23         188    211
3         100     8.9981       5          76     81
4          33    31.0009     242         230    472
..        ...        ...     ...         ...    ...
430        35     0.0000      52         161    213
431        83     7.0015      66          96    162
432        47    16.9979      30          88    118
433        57    19.9995       9          52     61
434        70    11.0014       4         237    241

[435 rows x 12 columns]

In [4]:
#1
# 데이터 형식 변경
df = df.astype({'datetime' : 'datetime64[ns]', 'season' : 'object', 'workingday' : 'object', 'holiday' : 'object'})
df_sub = df.loc[df.season ==1, ]

# 시간 정보 추출
df_sub['hour'] = df_sub['datetime'].dt.hour

# 계절별 및 시간대별 대여량 합계 계산 -> 오타인듯, 필요 없는 코딩
summary_data = df_sub.groupby(['season', 'hour']).agg({'count':'sum'}).reset_index()

# count가 가장 큰 hour 찾기
max_count_hour = df_sub.loc[df_sub['count'].idxmax(), 'hour']
max_count = df['count'].max()

print(f"count가 가장 큰 hour는 {max_count_hour}시이며, 대여량은 {max_count}입니다.")

count가 가장 큰 hour는 17시이며, 대여량은 970입니다.

<ipython-input-4-c56ad243f920>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub['hour'] = df_sub['datetime'].dt.hour

In [ ]:
#2
# 계절별로 그룹화하여 평균 대여량 계산
season_avg = df.groupby('season')['count'].mean().reset_index()
print(season_avg)

   season       count
0       1  103.169811
1       2  218.803922
2       3  265.500000
3       4  218.581197

In [5]:
#3
# 월 정보 추출
df['month'] = df['datetime'].dt.month

# 특정 월(1월) 필터링
january_rentals = df[df['month'] == 1]['count'].sum()
print(f"1월 동안의 총 대여량은 {january_rentals} 입니다.")

1월 동안의 총 대여량은 2567 입니다.

In [6]:
#4

# 날짜 정보 추출
df['date'] = df['datetime'].dt.date

# 날짜별로 대여량 합계 계산
date_rentals = df.groupby('date')['count'].sum()

# 가장 대여량이 많은 날짜 찾기
max_rental_date = date_rentals.idxmax()
max_rental_count = date_rentals.max()
print(f"가장 대여량이 많은 날짜는 {max_rental_date}이며, 대여량은 {max_rental_count}입니다.")

가장 대여량이 많은 날짜는 2012-05-11이며, 대여량은 1398입니다.

In [8]:
#5

df['hour'] = df['datetime'].dt.hour

df_average_hour_count = df.groupby('hour')['count'].mean().reset_index()
print(df_average_hour_count)

    hour       count
0      0   43.500000
1      1   52.714286
2      2   32.842105
3      3   12.000000
4      4    6.687500
5      5   17.750000
6      6   58.705882
7      7  208.937500
8      8  483.055556
9      9  260.117647
10    10  144.130435
11    11  182.000000
12    12  277.533333
13    13  290.600000
14    14  266.842105
15    15  255.666667
16    16  373.052632
17    17  519.200000
18    18  447.769231
19    19  322.103448
20    20  210.083333
21    21  196.619048
22    22  113.560000
23    23   77.352941

In [10]:
#6

df['weekday'] = df['datetime'].dt.day_name()

monday_count_sum = df[df['weekday'] == 'Monday']['count'].sum()

print(f"월요일 동안의 총 대여량은 {monday_count_sum}입니다.")

월요일 동안의 총 대여량은 10191입니다.

In [12]:
#7

# melt를 사용하여 긴 형식으로 변환
melted_df = df.melt(id_vars = ['datetime', 'season'],
                    var_name = 'user_type',
                    value_vars = ['casual', 'registered'],
                    value_name = 'rental_count')
print(melted_df)

               datetime season   user_type  rental_count
0   2011-09-05 17:00:00      3      casual            37
1   2011-05-17 11:00:00      2      casual            26
2   2011-11-10 09:00:00      4      casual            23
3   2011-10-13 07:00:00      4      casual             5
4   2011-10-15 14:00:00      4      casual           242
..                  ...    ...         ...           ...
865 2011-04-07 16:00:00      2  registered           161
866 2011-09-03 22:00:00      3  registered            96
867 2011-11-12 22:00:00      4  registered            88
868 2012-04-11 23:00:00      2  registered            52
869 2012-01-06 09:00:00      1  registered           237

[870 rows x 4 columns]

In [19]:
#8

# season과 user_type별로 그룹화하여 평균 대여 수 계산
avg_rentals = melted_df.groupby(['season', 'user_type'])['rental_count'].mean().reset_index()
print("각 계절별 user_type의 평균 대여 수:")
print(avg_rentals)

각 계절별 user_type의 평균 대여 수:
   season   user_type  rental_count
0       1      casual     14.122642
1       1  registered     89.047170
2       2      casual     48.990196
3       2  registered    169.813725
4       3      casual     55.127273
5       3  registered    210.372727
6       4      casual     29.709402
7       4  registered    188.871795

In [21]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/logdata.csv')

In [24]:
#9
print(df.info())

df['연도 정보'] = df['로그'].str.extract(r'(\d+)')
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   로그      30 non-null     object
dtypes: object(1)
memory usage: 372.0+ bytes
None
                                                  로그 연도 정보
0  2024-07-18 12:34:56 User: 홍길동 Action: Login ID...  2024
1  2024-07-18 12:35:00 User: 김철수 Action: Purchase...  2024
2  2024-07-18 12:36:10 User: 이영희 Action: Logout T...  2024
3  2024-07-18 12:37:22 User: 박지성 Action: Login ID...  2024
4  2024-07-18 12:38:44 User: 최강타 Action: Purchase...  2024

In [26]:
#10
df['시간 정보'] = df['로그'].str.extract(r'(\d{2}:\d{2}:\d{2})')
print(df[['로그', '시간 정보']].head())

                                                  로그     시간 정보
0  2024-07-18 12:34:56 User: 홍길동 Action: Login ID...  12:34:56
1  2024-07-18 12:35:00 User: 김철수 Action: Purchase...  12:35:00
2  2024-07-18 12:36:10 User: 이영희 Action: Logout T...  12:36:10
3  2024-07-18 12:37:22 User: 박지성 Action: Login ID...  12:37:22
4  2024-07-18 12:38:44 User: 최강타 Action: Purchase...  12:38:44

In [28]:
#11
df['한글 정보'] = df['로그'].str.extract(r'([가-힣]+)')
print(df[['로그', '한글 정보']].head())

                                                  로그 한글 정보
0  2024-07-18 12:34:56 User: 홍길동 Action: Login ID...   홍길동
1  2024-07-18 12:35:00 User: 김철수 Action: Purchase...   김철수
2  2024-07-18 12:36:10 User: 이영희 Action: Logout T...   이영희
3  2024-07-18 12:37:22 User: 박지성 Action: Login ID...   박지성
4  2024-07-18 12:38:44 User: 최강타 Action: Purchase...   최강타

In [31]:
#12
df['특수 문자 제거'] = df['로그'].str.replace(r'[^a-zA-Z0-9가-힣\s]', '', regex = True)
print(df['특수 문자 제거'])

0         20240718 123456 User 홍길동 Action Login ID12345
1     20240718 123500 User 김철수 Action Purchase Amoun...
2       20240718 123610 User 이영희 Action Logout Time 30s
3         20240718 123722 User 박지성 Action Login ID67890
4     20240718 123844 User 최강타 Action Purchase Amoun...
5       20240718 123950 User 장보고 Action Logout Time 25s
6     20240718 124056 User 홍길동 Action Purchase Amoun...
7         20240718 124100 User 김철수 Action Login ID23456
8     20240718 124210 User 이영희 Action Purchase Amoun...
9       20240718 124322 User 박지성 Action Logout Time 45s
10        20240718 124444 User 최강타 Action Login ID78901
11    20240718 124550 User 장보고 Action Purchase Amoun...
12      20240718 124656 User 홍길동 Action Logout Time 35s
13    20240718 124700 User 김철수 Action Purchase Amoun...
14        20240718 124810 User 이영희 Action Login ID56789
15    20240718 124922 User 박지성 Action Purchase Amoun...
16      20240718 125044 User 최강타 Action Logout Time 50s
17        20240718 125150 User 장보고 Action Login ID34567
18    20240718 125256 User 홍길동 Action Purchase Amoun...
19      20240718 125300 User 김철수 Action Logout Time 20s
20    20240718 125410 User 이영희 Action Purchase Amoun...
21        20240718 125522 User 박지성 Action Login ID12346
22    20240718 125644 User 최강타 Action Purchase Amoun...
23      20240718 125750 User 장보고 Action Logout Time 55s
24        20240718 125856 User 홍길동 Action Login ID67891
25    20240718 125900 User 김철수 Action Purchase Amoun...
26      20240718 130010 User 이영희 Action Logout Time 40s
27    20240718 130122 User 박지성 Action Purchase Amoun...
28        20240718 130244 User 최강타 Action Login ID78902
29    20240718 130350 User 장보고 Action Purchase Amoun...
Name: 특수 문자 제거, dtype: object

In [32]:
#13
df['Amount'] = df['로그'].str.extract(r'Amount:\s*(\d+)').astype(float)
df['User'] = df['로그'].str.extract(r'User:\s*([가-힣]+)')
grouped = df.groupby('User')['Amount'].mean().reset_index()

print("그룹별 평균 Amount 계산:")
print(grouped)

그룹별 평균 Amount 계산:
  User       Amount
0  김철수  3666.666667
1  박지성  5750.000000
2  이영희  4250.000000
3  장보고  5750.000000
4  최강타  3750.000000
5  홍길동  4250.000000